version: "3.8"

services:

  # Grafana - Metrics and logs visualization dashboard
  grafana:
    image: grafana/grafana:10.4.2
    user: "${USER_ID:-472}"
    volumes:
      - ./config/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring

  # Loki - Log aggregation system
  loki:
    image: grafana/loki:2.9.8
    volumes:
      - ./config/loki:/etc/loki
      - ./data/loki:/var/lib/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - monitoring

  # Promtail - Log collector and shipper for Loki
  promtail:
    image: grafana/promtail:2.9.8
    volumes:
      - /var/log:/var/log
      - ./config/promtail:/etc/promtail
      - ./data/promtail:/var/lib/promtail
    ports:
      - "9080:9080"  # Promtail HTTP server (optional)
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - monitoring

  # Prometheus - Metrics collection and monitoring system
  prometheus:
    image: prom/prometheus:v2.51.1
    volumes:
      - ./config/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - alertmanager
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  # Alertmanager - Handles alerts sent by Prometheus and sends notifications
  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: unless-stopped
    networks:
      - monitoring

  # Node Exporter - Collects host hardware and OS metrics
  node-exporter:
    image: prom/node-exporter:v1.8.1
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

networks:
  monitoring:
